# Generated by Django 4.0.3 on 2022-06-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_text', models.TextField()),
                ('who_wrote_it', models.CharField(choices=[], max_length=250, null=True)),
                ('relation', models.CharField(choices=[], max_length=250, null=True)),
                ('relation_elaboration', models.TextField(null=True)),
            ],
        ),
    ]
