# Generated by Django 4.0.4 on 2022-06-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bend', '0002_predictmodel_remove_emailbody_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictmodel',
            name='body_text',
            field=models.TextField(null=True),
        ),
    ]
